ReplaceFood: false
# this selection will remove the food bar completely and will show the thirst bar instead
Thirst:
  Max: 100
  Time: 100
  # 20 tick = 1 second
  DecreasePerTime: 1
DamagePerSecond: 0.5
# damage value per second when your thirst bar returns to 0
BossBar:
  Enable: true
  Title: <thirstValue>/<thirstMax> - <thirstDecrease>
  Color: BLUE
  # See all colors at:
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Color.html
  Style: SEGMENTED_10
  # All styles of BossBar
  # SEGMENTED_10
  # SEGMENTED_12
  # SEGMENTED_20
  # SEGMENTED_6
  # SOLID
# Permission to use the commands of thirstBar
RefreshMessage: '&a<player> has been refreshed.'
ImmuneMessage: '&aImmune <player> has been set.'
DisableMessage: '&aDisable thirst <player> has been set.'
SetThirstValueMessage: '&e<player> has been set thirst value to <value>.'
CheckThirstValueMessage: '&eThe thirst value of <player> is <value>/<valueMax>.'
DontHavePermissionMessage: '&cYou don't have permission to use this command.'
ItemConsumeRegen:
  - carrot:2
  - potion:20
  - golden_apple:50
  - enchanted_golden_apple:75
  - milk_bucket:100
# - <material>:<value>
# Thirst value will be restored when you eat
# or drink the following materials